#ifndef __RESOURCE_H__
#define __RESOURCE_H__

// Icon resources.
#define APPICON         0x01

// Sound resources.
#define SOUND_GAME_OVER_1   0x01
#define SOUND_POWER_UP      0x02
#define MUSIC_RETRO         0x03
#define SOUND_START         0x04

// String resources.
#define IDS_EMPTY           0xffffff
#define IDS_APP_NAME        1

// English strings (Default).
#define IDS_LANGUAGE        100
#define IDS_SPAN_1          101
#define IDS_SPAN_2          102
#define IDS_SPAN_3          103
#define IDS_FRUIT_1         104
#define IDS_FRUIT_2         105
#define IDS_FRUIT_3         106
#define IDS_FRUIT_4         108
#define IDS_FRUIT_MSG_1     109
#define IDS_FRUIT_MSG_2     110
#define IDS_GAMEOVER        111
#define IDS_PAUSE           112
#define IDS_PLAY            113
#define IDS_SETTINGS        114
#define IDS_LEAVE_GAME      115
#define IDS_EXIT            116
#define IDS_SCORE           117
#define IDS_LAST_SCORE      118
#define IDS_LANG_SELECT     119
#define IDS_OK              120
#define IDS_SETTINGS_LANG   121
#define IDS_SETTINGS_SOUND  122
#define IDS_PLAY_AGAIN      123
#define IDS_ENABLE          124
#define IDS_DISABLE         125

// Afrikaans strings.
#define IDS_AF_LANGUAGE         200
#define IDS_AF_SPAN_1           201
#define IDS_AF_SPAN_2		    202
#define IDS_AF_SPAN_3		    203
#define IDS_AF_FRUIT_1          204
#define IDS_AF_FRUIT_2		    205
#define IDS_AF_FRUIT_3		    206
#define IDS_AF_FRUIT_4		    208
#define IDS_AF_FRUIT_MSG_1      209
#define IDS_AF_FRUIT_MSG_2      210
#define IDS_AF_GAMEOVER         211
#define IDS_AF_PAUSE            212
#define IDS_AF_PLAY             213
#define IDS_AF_SETTINGS         214
#define IDS_AF_LEAVE_GAME       215
#define IDS_AF_EXIT             216
#define IDS_AF_SCORE            217
#define IDS_AF_LAST_SCORE       218
#define IDS_AF_LANG_SELECT      219
#define IDS_AF_OK               220
#define IDS_AF_SETTINGS_LANG    221
#define IDS_AF_SETTINGS_SOUND   222
#define IDS_AF_PLAY_AGAIN       223
#define IDS_AF_ENABLE           224
#define IDS_AF_DISABLE          225

// Arabic strings.
#define IDS_AR_LANGUAGE         300
#define IDS_AR_SPAN_1           301
#define IDS_AR_SPAN_2           302
#define IDS_AR_SPAN_3           303
#define IDS_AR_FRUIT_1          304
#define IDS_AR_FRUIT_2          305
#define IDS_AR_FRUIT_3          306
#define IDS_AR_FRUIT_4          308
#define IDS_AR_FRUIT_MSG_1      309
#define IDS_AR_FRUIT_MSG_2      310
#define IDS_AR_GAMEOVER         311
#define IDS_AR_PAUSE            312
#define IDS_AR_PLAY             313
#define IDS_AR_SETTINGS         314
#define IDS_AR_LEAVE_GAME       315
#define IDS_AR_EXIT             316
#define IDS_AR_SCORE            317
#define IDS_AR_LAST_SCORE       318
#define IDS_AR_LANG_SELECT      319
#define IDS_AR_OK               320
#define IDS_AR_SETTINGS_LANG    321
#define IDS_AR_SETTINGS_SOUND   322
#define IDS_AR_PLAY_AGAIN       323
#define IDS_AR_ENABLE           324
#define IDS_AR_DISABLE          325

// Chinese strings.
#define IDS_ZH_LANGUAGE         400
#define IDS_ZH_SPAN_1           401
#define IDS_ZH_SPAN_2           402
#define IDS_ZH_SPAN_3           403
#define IDS_ZH_FRUIT_1          404
#define IDS_ZH_FRUIT_2          405
#define IDS_ZH_FRUIT_3          406
#define IDS_ZH_FRUIT_4          408
#define IDS_ZH_FRUIT_MSG_1      409
#define IDS_ZH_FRUIT_MSG_2      410
#define IDS_ZH_GAMEOVER         411
#define IDS_ZH_PAUSE            412
#define IDS_ZH_PLAY             413
#define IDS_ZH_SETTINGS         414
#define IDS_ZH_LEAVE_GAME       415
#define IDS_ZH_EXIT             416
#define IDS_ZH_SCORE            417
#define IDS_ZH_LAST_SCORE       418
#define IDS_ZH_LANG_SELECT      419
#define IDS_ZH_OK               420
#define IDS_ZH_SETTINGS_LANG    421
#define IDS_ZH_SETTINGS_SOUND   422
#define IDS_ZH_PLAY_AGAIN       423
#define IDS_ZH_ENABLE           424
#define IDS_ZH_DISABLE          425

// French strings.
#define IDS_FR_LANGUAGE         500
#define IDS_FR_SPAN_1           501
#define IDS_FR_SPAN_2           502
#define IDS_FR_SPAN_3           503
#define IDS_FR_FRUIT_1          504
#define IDS_FR_FRUIT_2          505
#define IDS_FR_FRUIT_3          506
#define IDS_FR_FRUIT_4          508
#define IDS_FR_FRUIT_MSG_1      509
#define IDS_FR_FRUIT_MSG_2      510
#define IDS_FR_GAMEOVER         511
#define IDS_FR_PAUSE            512
#define IDS_FR_PLAY             513
#define IDS_FR_SETTINGS         514
#define IDS_FR_LEAVE_GAME       515
#define IDS_FR_EXIT             516
#define IDS_FR_SCORE            517
#define IDS_FR_LAST_SCORE       518
#define IDS_FR_LANG_SELECT      519
#define IDS_FR_OK               520
#define IDS_FR_SETTINGS_LANG    521
#define IDS_FR_SETTINGS_SOUND   522
#define IDS_FR_PLAY_AGAIN       523
#define IDS_FR_ENABLE           524
#define IDS_FR_DISABLE          525

// Japanese strings.
#define IDS_JA_LANGUAGE         600
#define IDS_JA_SPAN_1           601
#define IDS_JA_SPAN_2		    602
#define IDS_JA_SPAN_3		    603
#define IDS_JA_FRUIT_1          604
#define IDS_JA_FRUIT_2		    605
#define IDS_JA_FRUIT_3		    606
#define IDS_JA_FRUIT_4		    608
#define IDS_JA_FRUIT_MSG_1      609
#define IDS_JA_FRUIT_MSG_2      610
#define IDS_JA_GAMEOVER         611
#define IDS_JA_PAUSE            612
#define IDS_JA_PLAY             613
#define IDS_JA_SETTINGS         614
#define IDS_JA_LEAVE_GAME       615
#define IDS_JA_EXIT             616
#define IDS_JA_SCORE            617
#define IDS_JA_LAST_SCORE       618
#define IDS_JA_LANG_SELECT      619
#define IDS_JA_OK               620
#define IDS_JA_SETTINGS_LANG    621
#define IDS_JA_SETTINGS_SOUND   622
#define IDS_JA_PLAY_AGAIN       623
#define IDS_JA_ENABLE           624
#define IDS_JA_DISABLE          625

// Korean strings.
#define IDS_KO_LANGUAGE         700
#define IDS_KO_SPAN_1           701
#define IDS_KO_SPAN_2           702
#define IDS_KO_SPAN_3           703
#define IDS_KO_FRUIT_1          704
#define IDS_KO_FRUIT_2          705
#define IDS_KO_FRUIT_3          706
#define IDS_KO_FRUIT_4          708
#define IDS_KO_FRUIT_MSG_1      709
#define IDS_KO_FRUIT_MSG_2      710
#define IDS_KO_GAMEOVER         711
#define IDS_KO_PAUSE            712
#define IDS_KO_PLAY             713
#define IDS_KO_SETTINGS         714
#define IDS_KO_LEAVE_GAME       715
#define IDS_KO_EXIT             716
#define IDS_KO_SCORE            717
#define IDS_KO_LAST_SCORE       718
#define IDS_KO_LANG_SELECT      719
#define IDS_KO_OK               720
#define IDS_KO_SETTINGS_LANG    721
#define IDS_KO_SETTINGS_SOUND   722
#define IDS_KO_PLAY_AGAIN       723
#define IDS_KO_ENABLE           724
#define IDS_KO_DISABLE          725

// Portuguese strings.
#define IDS_PT_LANGUAGE         800
#define IDS_PT_SPAN_1           801
#define IDS_PT_SPAN_2           802
#define IDS_PT_SPAN_3           803
#define IDS_PT_FRUIT_1          804
#define IDS_PT_FRUIT_2          805
#define IDS_PT_FRUIT_3          806
#define IDS_PT_FRUIT_4          808
#define IDS_PT_FRUIT_MSG_1      809
#define IDS_PT_FRUIT_MSG_2      810
#define IDS_PT_GAMEOVER         811
#define IDS_PT_PAUSE            812
#define IDS_PT_PLAY             813
#define IDS_PT_SETTINGS         814
#define IDS_PT_LEAVE_GAME       815
#define IDS_PT_EXIT             816
#define IDS_PT_SCORE            817
#define IDS_PT_LAST_SCORE       818
#define IDS_PT_LANG_SELECT      819
#define IDS_PT_OK               820
#define IDS_PT_SETTINGS_LANG    821
#define IDS_PT_SETTINGS_SOUND   822
#define IDS_PT_PLAY_AGAIN       823
#define IDS_PT_ENABLE           824
#define IDS_PT_DISABLE          825

// Russian strings.
#define IDS_RU_LANGUAGE         900
#define IDS_RU_SPAN_1           901
#define IDS_RU_SPAN_2           902
#define IDS_RU_SPAN_3           903
#define IDS_RU_FRUIT_1          904
#define IDS_RU_FRUIT_2          905
#define IDS_RU_FRUIT_3          906
#define IDS_RU_FRUIT_4          908
#define IDS_RU_FRUIT_MSG_1      909
#define IDS_RU_FRUIT_MSG_2      910
#define IDS_RU_GAMEOVER         911
#define IDS_RU_PAUSE            912
#define IDS_RU_PLAY             913
#define IDS_RU_SETTINGS         914
#define IDS_RU_LEAVE_GAME       915
#define IDS_RU_EXIT             916
#define IDS_RU_SCORE            917
#define IDS_RU_LAST_SCORE       918
#define IDS_RU_LANG_SELECT      919
#define IDS_RU_OK               920
#define IDS_RU_SETTINGS_LANG    921
#define IDS_RU_SETTINGS_SOUND   922
#define IDS_RU_PLAY_AGAIN       923
#define IDS_RU_ENABLE           924
#define IDS_RU_DISABLE          925

// Spanish strings.
#define IDS_ES_LANGUAGE         1000
#define IDS_ES_SPAN_1           1001
#define IDS_ES_SPAN_2		    1002
#define IDS_ES_SPAN_3		    1003
#define IDS_ES_FRUIT_1          1004
#define IDS_ES_FRUIT_2		    1005
#define IDS_ES_FRUIT_3		    1006
#define IDS_ES_FRUIT_4		    1008
#define IDS_ES_FRUIT_MSG_1      1009
#define IDS_ES_FRUIT_MSG_2      1010
#define IDS_ES_GAMEOVER         1011
#define IDS_ES_PAUSE            1012
#define IDS_ES_PLAY             1013
#define IDS_ES_SETTINGS         1014
#define IDS_ES_LEAVE_GAME       1015
#define IDS_ES_EXIT             1016
#define IDS_ES_SCORE            1017
#define IDS_ES_LAST_SCORE       1018
#define IDS_ES_LANG_SELECT      1019
#define IDS_ES_OK               1020
#define IDS_ES_SETTINGS_LANG    1021
#define IDS_ES_SETTINGS_SOUND   1022
#define IDS_ES_PLAY_AGAIN       1023
#define IDS_ES_ENABLE           1024
#define IDS_ES_DISABLE          1025

// Turkish strings.
#define IDS_TR_LANGUAGE         1100
#define IDS_TR_SPAN_1           1101
#define IDS_TR_SPAN_2		    1102
#define IDS_TR_SPAN_3		    1103
#define IDS_TR_FRUIT_1          1104
#define IDS_TR_FRUIT_2		    1105
#define IDS_TR_FRUIT_3		    1106
#define IDS_TR_FRUIT_4		    1108
#define IDS_TR_FRUIT_MSG_1      1109
#define IDS_TR_FRUIT_MSG_2      1110
#define IDS_TR_GAMEOVER         1111
#define IDS_TR_PAUSE            1112
#define IDS_TR_PLAY             1113
#define IDS_TR_SETTINGS         1114
#define IDS_TR_LEAVE_GAME       1115
#define IDS_TR_EXIT             1116
#define IDS_TR_SCORE            1117
#define IDS_TR_LAST_SCORE       1118
#define IDS_TR_LANG_SELECT      1119
#define IDS_TR_OK               1120
#define IDS_TR_SETTINGS_LANG    1121
#define IDS_TR_SETTINGS_SOUND   1122
#define IDS_TR_PLAY_AGAIN       1123
#define IDS_TR_ENABLE           1124
#define IDS_TR_DISABLE          1125

#endif
/*
 *	End Of File
 */
